package model;

public enum Teams {
    LAKERS, ATLANTA_HAWKS, DETROIT_PISTONS, CLEVELAND_CAVALIERS, NEW_YORK_KNICKS,
    MINNESOTA_TIMBERWOLVES, CHARLOTTE_HORNETS, WASHINGTON_WIZARDS, CHICAGO_BULLS, GOLDEN_STATE_WARRIORS;
}
